"""add notifications and lesiones tables

Revision ID: 1bea8f9c9ff0
Revises: add_fecha_vencimiento_rutinas
Create Date: 2025-08-18 21:12:35.772770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bea8f9c9ff0'
down_revision = 'add_fecha_vencimiento_rutinas'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lesiones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alumno_id', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(length=100), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('es_cronica', sa.Boolean(), nullable=True),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=True),
    sa.Column('fecha_fin', sa.DateTime(), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=True),
    sa.Column('creada_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['alumno_id'], ['alumnos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coach_id', sa.Integer(), nullable=True),
    sa.Column('alumno_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('titulo', sa.String(length=200), nullable=True),
    sa.Column('mensaje', sa.Text(), nullable=True),
    sa.Column('leida', sa.Boolean(), nullable=True),
    sa.Column('creada_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['alumno_id'], ['alumnos.id'], ),
    sa.ForeignKeyConstraint(['coach_id'], ['coaches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_rutinas_plantilla_coach_id', 'rutinas_plantilla', ['coach_id'], unique=False)
    op.create_index('idx_rutinas_eliminado', 'rutinas', ['eliminado'], unique=False)
    op.create_index('idx_rutinas_alumno_id', 'rutinas', ['alumno_id'], unique=False)
    op.create_index('idx_rutinas_activa', 'rutinas', ['activa'], unique=False)
    op.create_index('idx_pesos_alumno_fecha', 'pesos_alumno', ['fecha'], unique=False)
    op.create_index('idx_pesos_alumno_alumno_id', 'pesos_alumno', ['alumno_id'], unique=False)
    op.create_index('idx_personal_records_fecha', 'personal_records', ['fecha'], unique=False)
    op.create_index('idx_personal_records_ejercicio', 'personal_records', ['ejercicio'], unique=False)
    op.create_index('idx_personal_records_alumno_id', 'personal_records', ['alumno_id'], unique=False)
    op.create_index('idx_ejercicios_rutina_id', 'ejercicios', ['rutina_id'], unique=False)
    op.create_index('idx_ejercicios_ejercicio_base_id', 'ejercicios', ['ejercicio_base_id'], unique=False)
    op.create_index('idx_dietas_plantilla_coach_id', 'dietas_plantilla', ['coach_id'], unique=False)
    op.create_index('idx_dietas_eliminado', 'dietas', ['eliminado'], unique=False)
    op.create_index('idx_dietas_alumno_id', 'dietas', ['alumno_id'], unique=False)
    op.create_index('idx_dietas_activa', 'dietas', ['activa'], unique=False)
    op.create_index('idx_comidas_dieta_id', 'comidas', ['dieta_id'], unique=False)
    op.create_index('idx_comida_alimentos_comida_id', 'comida_alimentos', ['comida_id'], unique=False)
    op.create_index('idx_comida_alimentos_alimento_id', 'comida_alimentos', ['alimento_id'], unique=False)
    op.create_index('idx_alumnos_notificaciones_activas', 'alumnos', ['notificaciones_activas'], unique=False)
    op.create_index('idx_alumnos_fecha_cobro', 'alumnos', ['fecha_cobro'], unique=False)
    op.create_index('idx_alumnos_coach_id', 'alumnos', ['coach_id'], unique=False)
    op.drop_table('notifications')
    op.drop_table('lesiones')
    # ### end Alembic commands ###